### ISSUE TITLE
Inconsistent UI in Unified Inventory

### ISSUE THREAD

**Issue by insanity54** [SmallJoker/upgrade_packs#1]
Hi there! Thanks for this mod! I really like having more HP in-game. It helps massively as I love to build skyscrapers and often fall to my death!

I'm running Unified Inventory on my server, and the UI seemed a little wonky. The inventory was squished up against the left side of the inventory window and the heading was in a place that didn't match other Unified Inventory mods.

![screenshot_20221213_071346](https://user-images.githubusercontent.com/670375/207372292-1096accb-55b7-4fd6-b28e-9933889083e9.png)

I went ahead and tweaked it a little bit, and I think it looks a lot more consistent with Unified Inventory styling.

![screenshot_20221213_071348](https://user-images.githubusercontent.com/670375/207372632-539ea501-afba-4141-9512-bee3a77ff186.png)

I'll drop a PR in case it is helpful. Thanks again!

**Comment by SmallJoker** [comment]
#2
